- name: Configure Docker on all nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker daemon.json exists
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["211.183.3.198"]
          }
      notify:
        - Restart Docker

    - name: Ensure Docker certs directory exists
      file:
        path: /etc/docker/certs.d/211.183.3.198
        state: directory
        mode: '0755'

    - name: Copy Harbor certificate
      copy:
        src: /etc/docker/certs.d/211.183.3.198/ca.crt
        dest: /etc/docker/certs.d/211.183.3.198/ca.crt
        mode: '0644'
      notify:
        - Restart Docker
        
    - name: Pull Docker Image
      shell: docker pull 211.183.3.198/myproject/keduitlab:white
        
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted

- name: Deploy Kubernetes resources
  hosts: master
  become: true
  tasks:
    - name: Create deployment.yaml from template
      template:
        src: deployment.yaml
        dest: /tmp/deployment.yaml

    - name: Create service.yaml from template
      template:
        src: service.yaml
        dest: /tmp/service.yaml

    - name: Apply deployment
      shell: kubectl apply -f /tmp/deployment.yaml

    - name: Apply service
      shell: kubectl apply -f /tmp/service.yaml
