- name: Configure Docker on all nodes  # 모든 노드에서 Docker 설정 구성
  hosts: all
  become: true
  tasks:
    - name: Docker 설정 파일 존재 여부 확인 및 생성
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["211.183.3.198"]
          }
      notify:
        - Restart Docker

    - name: Docker 인증서 디렉토리 확인 및 생성
      file:
        path: /etc/docker/certs.d/211.183.3.198
        state: directory
        mode: '0755'

    - name: Harbor 인증서를 Docker 인증서 디렉토리에 복사
      copy:
        src: /path/to/local/ca.crt  # 인증서의 로컬 경로 (수정 필요)
        dest: /etc/docker/certs.d/211.183.3.198/ca.crt
        mode: '0644'
      notify:
        - Restart Docker

    - name: Harbor에서 Docker 이미지를 Pull
      shell: docker pull 211.183.3.198/myproject/keduitlab:springboot  # 이미지 태그 수정
      become: true

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted

- name: Kubernetes 리소스 배포
  hosts: master
  become: true
  tasks:
    - name: Create deployment.yaml from template
      copy:
        src: /path/to/local/deployment.yaml  # 로컬의 deployment.yaml 경로
        dest: /tmp/deployment.yaml

    - name: Create service.yaml from template
      copy:
        src: /path/to/local/service.yaml  # 로컬의 service.yaml 경로
        dest: /tmp/service.yaml

    - name: Apply deployment
      shell: kubectl apply -f /tmp/deployment.yaml

    - name: Apply service
      shell: kubectl apply -f /tmp/service.yaml
