apiVersion: v1
kind: Service
metadata:
  name: springboot-service  # 이름 변경 (더 명확하게)
spec:
  type: LoadBalancer  # 외부 트래픽을 LoadBalancer를 통해 전달
  selector:
    app: springboot-app  # Deployment와 일치하는 레이블e
  ports:
  - protocol: TCP
    port: 80            # 외부에서 접근할 포트d
    targetPort: 8080    # Spring Boot 컨테이너의 포트d
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: my-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
