name: CI/CD Pipeline with GitHub Actions

on:
  push:
    branches:
      - main  # main 브랜치 푸시 시 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      HARBOR_URL: '211.183.3.198'
      HARBOR_REPO: 'myproject/keduitlab'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # GitHub 레포지토리 체크아웃

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Docker 빌드 환경 설정

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASS }}" | docker login $HARBOR_URL -u ${{ secrets.HARBOR_USER }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $HARBOR_URL/$HARBOR_REPO:white .
          docker push $HARBOR_URL/$HARBOR_REPO:white

      - name: Set up SSH for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ secrets.MASTER_NODE_IP }}, -u ${{ secrets.SSH_USER }} deploy.yml
